steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
        '-c',
        'docker pull
        europe-west3-docker.pkg.dev/gmail-reminder-api/cloud-run-source-deploy/crew:latest || exit 0',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'kulturspektakel.de/gmail-reminder-api/cloud-run-source-deploy/crew:latest',
        '--cache-from',
        'europe-west3-docker.pkg.dev/gmail-reminder-api/cloud-run-source-deploy/crew:latest',
        '.',
      ]
images:
  - 'europe-west3-docker.pkg.dev/gmail-reminder-api/cloud-run-source-deploy/crew:latest'
options:
  logging: CLOUD_LOGGING_ONLY
