schema: https://api.kulturspektakel.de/graphql
documents:
  - ./src/**/*.ts
  - ./src/**/*.tsx
generates:
  ./src/utils/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  ./src/utils/graphql.schema.json:
    plugins:
      - introspection
    config:
      minify: true
config:
  withMutationFn: true
  scalars:
    Date: Date
    DateTime: Date
hooks:
  afterOneFileWrite:
    - prettier --write
