schema: https://api.kulturspektakel.de/graphql
documents:
  - ../**/*.ts
  - ../**/*.tsx
generates:
  ./graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  ./graphql.schema.json:
    plugins:
      - introspection
    config:
      minify: true
config:
  withMutationFn: true
  scalars:
    Date: Date
    DateTime: Date
hooks:
  afterOneFileWrite:
    - prettier --write
