name: Deploy

on:
  push:
    branches:
      - gcp

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_JSON }}'

      - name: 'deploy'
        env:
          Dotenv: ${{ secrets.DOTENV_ME }}
        run: |
          echo "DOTENV_ME=$Dotenv" > .env.me
          npm install
          npx dotenv-vault pull
          npx dotenv-vault pull production
          npx ts-node scripts/merge-envs.ts
          npm run build
          gcloud meta list-files-for-upload
          gcloud builds submit --config cloudbuild.yaml .
          gcloud run deploy crew --image europe-west1-docker.pkg.dev/gmail-reminder-api/cloud-run-source-deploy/crew:latest --env-vars-file ./.env.json --region europe-west1 --allow-unauthenticated
