name: Deploy

on:
  push:
    branches:
      - gcp

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - name: Prepare environment
        env:
          Dotenv: ${{ secrets.DOTENV_ME }}
        run: |
          echo "DOTENV_ME=$Dotenv" > .env.me
          yarn
          yarn dotenv-vault pull
          yarn dotenv-vault pull production
          yarn ts-node scripts/merge-envs.ts
          rm -rf .env.me

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_JSON }}'

      - name: 'deploy'
        run: |
          gcloud builds submit --config cloudbuild.yaml .
          gcloud run deploy crew --image kulturspektakel.de/crew:latest --env-vars-file ./env.json --region europe-west3 --allow-unauthenticated
